package kg.itg.tirexchange;

import com.axelor.app.AxelorModule;
import kg.itg.tirexchange.mapper.EpdDtoMapper;
import kg.itg.tirexchange.mapper.EpdDtoMapperImpl;
import kg.itg.tirexchange.mapper.TirMessageMapper;
import kg.itg.tirexchange.mapper.TirMessageMapperImpl;
import kg.itg.tirexchange.service.TirMessageService;
import kg.itg.tirexchange.service.TirMessageServiceImpl;

/**
 * Guice bindings for the TIR Exchange module (replaces Spring component
 * scanning). AOP auto-discovers {@link AxelorModule} subclasses on the
 * classpath and runs {@link #configure()} at startup.
 *
 * <p>Processors, {@code EpdFactory} and {@code TirXmlMapper} are concrete
 * classes with {@code @Inject} constructors, so Guice wires them implicitly;
 * only the interface → implementation bindings need to be declared here.
 * The {@code *Impl} mappers are generated by MapStruct at build time.
 */
public class TirExchangeModule extends AxelorModule {

    @Override
    protected void configure() {
        bind(TirMessageService.class).to(TirMessageServiceImpl.class);
        bind(EpdDtoMapper.class).to(EpdDtoMapperImpl.class);
        bind(TirMessageMapper.class).to(TirMessageMapperImpl.class);
    }
}
