package kg.itg.tirexchange.db.repo;

import kg.itg.tirexchange.db.TirMessage;

import java.util.List;

/**
 * Repository for {@link TirMessage}. Extends the {@code AbstractTirMessageRepository}
 * generated by AOP from {@code domains/TirMessage.xml}, which already provides
 * {@code all()}, {@code find(id)}, {@code save(entity)} and {@code remove(entity)}.
 *
 * <p>Replaces the Spring Data {@code JpaRepository} query-derivation methods with
 * explicit AOP {@code Query} calls.
 */
public class TirMessageRepository extends AbstractTirMessageRepository {

    /** All messages for a guarantee number (replaces the derived finder). */
    public List<TirMessage> findByGuaranteeNumber(final String guaranteeNumber) {
        return all()
                .filter("self.guaranteeNumber = :guaranteeNumber")
                .bind("guaranteeNumber", guaranteeNumber)
                .fetch();
    }

    /** A page of messages for a guarantee number, ordered by id. */
    public List<TirMessage> findByGuaranteeNumber(final String guaranteeNumber,
                                                  final int page,
                                                  final int size) {
        return all()
                .filter("self.guaranteeNumber = :guaranteeNumber")
                .bind("guaranteeNumber", guaranteeNumber)
                .order("id")
                .fetch(size, page * size);
    }

    public long countByGuaranteeNumber(final String guaranteeNumber) {
        return all()
                .filter("self.guaranteeNumber = :guaranteeNumber")
                .bind("guaranteeNumber", guaranteeNumber)
                .count();
    }

    /** A page of messages for a message type, ordered by id. */
    public List<TirMessage> findByMessageType(final String messageType,
                                              final int page,
                                              final int size) {
        return all()
                .filter("self.messageType = :messageType")
                .bind("messageType", messageType)
                .order("id")
                .fetch(size, page * size);
    }

    public long countByMessageType(final String messageType) {
        return all()
                .filter("self.messageType = :messageType")
                .bind("messageType", messageType)
                .count();
    }

    /** A page of all messages, ordered by id. */
    public List<TirMessage> findAll(final int page, final int size) {
        return all().order("id").fetch(size, page * size);
    }
}
